In [4]:
!pip install numpy

import numpy as np

In [2]:
a = np.array([1,2,3,4,'a'])

<IPython.core.display.Javascript object>

In [3]:
a

array(['1', '2', '3', '4', 'a'], dtype='<U11')

In [5]:
a = np.array(10)
b = np.array([1,2,3])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [6]:
print('a dimesion:', a.ndim)
print('b dimesion:', b.ndim)
print('c dimesion:', c.ndim)
print('d dimesion:', d.ndim)

a dimesion: 0
b dimesion: 1
c dimesion: 2
d dimesion: 3


In [7]:
print(a)
print('shape of a:', a.shape)
print(b)
print('shape of a:', b.shape)
print(c)
print('shape of a:', c.shape)
print(d)
print('shape of a:', d.shape)

10
shape of a: ()
[1 2 3]
shape of a: (3,)
[[1 2 3]
 [4 5 6]]
shape of a: (2, 3)
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
shape of a: (2, 2, 3)


In [9]:
print(c.dtype)
print(d.dtype)

int32
int32


In [10]:
print(type(a))
print(type(b))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [11]:
len(d)

2

In [12]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [15]:
np.eye(6, dtype = float)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [16]:
np.zeros((3, 5),dtype='int')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [17]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
np.full((3, 2), 10,dtype=int)

array([[10, 10],
       [10, 10],
       [10, 10]])

In [19]:
np.full((2, 3), 111,dtype=int)

array([[111, 111, 111],
       [111, 111, 111]])

In [20]:
x = [1,2,3,4,5,6,7]
np.diag(x)

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 7]])

In [21]:
x = np.arange(1, 17)
print(x)
print(x.shape)
print(x.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
(16,)
1


In [22]:
n=x.reshape((8,2))
print(n)
print(n.shape)
print(n.ndim)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]
(8, 2)
2


In [23]:
n1=n.reshape((4,2,2))
print(n1)
print(n1.shape)
print(n1.ndim)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]
(4, 2, 2)
3


In [24]:
v=n.ravel()
print(v.shape)
print(v)
print(v.ndim)

(16,)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
1


In [25]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [26]:
a = np.arange(2,17,2)

a

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [27]:
a[2]

6

In [28]:
a[0:7:2]

array([ 2,  6, 10, 14])

In [29]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
a[2,2]

9

In [31]:
b = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
b.shape
b

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [32]:
b[0][1][2]

6

In [34]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
arr[0:5]

array([1, 2, 3, 4, 5])

In [36]:
arr[5:]

array([ 6,  7,  8,  9, 10])

In [37]:
arr[1:7:2]

array([2, 4, 6])

In [38]:
arr[0:10:2]

array([1, 3, 5, 7, 9])

In [39]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
arr[2]

3

In [41]:
a[0:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [42]:
x1= np.arange(10)
x1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
x2 = x1

In [44]:
print(x1)
print(x2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [45]:
x2[0]=10

In [46]:
print(x1)
print(x2)

[10  1  2  3  4  5  6  7  8  9]
[10  1  2  3  4  5  6  7  8  9]


In [47]:
print(id(x1))
print(id(x2))

1573027628880
1573027628880


In [48]:
print(np.shares_memory(x1, x2))
print(id(x1))
print(id(x2))

True
1573027628880
1573027628880


In [49]:
x3 = x1.view()

In [50]:
np.shares_memory(x1, x3)

True

In [51]:
x3[0] =100

In [56]:
print(x1)
print(x2)

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8   9]


In [59]:
print(id(x1))
print(id(x2))
np.shares_memory(x1, x2)

1573027628880
1573027628880


True

In [60]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
a > 3

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [62]:
a[a > 3]

array([4, 5, 6, 7, 8, 9])

In [63]:
a[(a > 3) & (a < 6)]

array([4, 5])

In [65]:
x1 == x2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [66]:
print(a.transpose())
print("------------")
print(a)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [67]:
print(x1)
print(x2)
np.vstack((x1, x2))

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8   9]


array([[100,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [100,   1,   2,   3,   4,   5,   6,   7,   8,   9]])

In [68]:
np.hstack((x1,x2))

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9, 100,   1,   2,
         3,   4,   5,   6,   7,   8,   9])

In [70]:
print(x1)
print(x2)
np.insert(x1, 4 , x2)

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8   9]


array([100,   1,   2,   3, 100,   1,   2,   3,   4,   5,   6,   7,   8,
         9,   4,   5,   6,   7,   8,   9])

In [71]:
print(x2)
np.delete(x2, 0)

[100   1   2   3   4   5   6   7   8   9]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [73]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [74]:
(np.sin(a))/(np.cos(a))

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619],
       [ 0.87144798, -6.79971146, -0.45231566]])

In [75]:
print(np.cos(a))
print(np.tan(a))

[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -6.79971146 -0.45231566]]


In [76]:
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [77]:
np.sum(a)

45

In [78]:
np.sum(a, axis=1)

array([ 6, 15, 24])

In [79]:
np.sum(a, axis=0)

array([12, 15, 18])

In [80]:
np.median(a)

5.0

In [82]:
np.mean(a)

5.0

In [83]:
np.std(a)

2.581988897471611

In [84]:
np.max(a)

9

In [85]:
np.sort(x2)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9, 100])

In [86]:
m=np.where(x1==4)
m

(array([4], dtype=int64),)

In [87]:
x1

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [88]:
c=np.array([44,55,66,88,99,12,12,12,12,10,10,10,101,0])


In [89]:
np.where(c%2 == 0)

(array([ 0,  2,  3,  5,  6,  7,  8,  9, 10, 11, 13], dtype=int64),)

In [90]:
np.where(x1>5, x1, 0)

array([100,   0,   0,   0,   0,   0,   6,   7,   8,   9])

In [91]:
print(dir(list))

['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']
